### ISSUE TITLE
RestClient ThrowOnAnyError is set to true

### ISSUE THREAD

**Issue by elansaro** [Mangopay/mangopay2-net-sdk#164]
Hello,

I've noticed that the following recent changes (< 2 months)

https://github.com/Mangopay/mangopay2-net-sdk/blob/15b2d78d732a1e09359d442501fc93f29c888013/MangoPay.SDK/Core/RestTool.cs#L26

have changed the behavior of the RestTool so that it throws a generic exception automatically when an API call returns a non success status here

https://github.com/Mangopay/mangopay2-net-sdk/blob/15b2d78d732a1e09359d442501fc93f29c888013/MangoPay.SDK/Core/RestTool.cs#L256

therefore, we exit the function before logging any errors using ILog or setting the last request infos, leaving it impossible to retrieve the underlying error.

**Comment by raphrbnt** [comment]
I've experienced the same problem after upgrading the SDK version to 3.3.1

A `System.Net.HttpResponseException` is thrown instead of `MangoPay.SDK.Core.ResponseException`, making the returned data in the failed response inaccessible, either programatically nor while debugging. This is quite annoying an can even be blocking in certain cases as we have no clue on what has been going wrong.

**Comment by fredericdelordm** [comment]
Hello @elansaro & @raphrbnt,

We are looking into it

**Comment by jbvovau** [comment]
@elansaro & @raphrbnt A fix is ready and will be deployed very soon. 
Pull request is pending : https://github.com/Mangopay/mangopay2-net-sdk/pull/169/files

I've got the same problem will this line, and received "BadRequest" error instead of usual Mangopay errors messages : 
` ThrowOnAnyError = true, `

**Comment by jbvovau** [comment]
New release is done.
