### ISSUE TITLE
exception non-catch result from currency

### ISSUE THREAD

**Issue by ycaoyang** [Mangopay/mangopay2-net-sdk#5]
Hello,

Knowing that Mangopay only accepts 8 currencys for now to do the payment, when we send a request with other currency, there will be a http reponse 400 which was thrown in method ``RestTool.CheckResponseCode()`` without catch any more.

As my opinion, how about to create an enum, named as ``CurrencyMangopay`` for instance, to avoid the currency exception from original ?

Anyway, the thrown exception was suggested to be catched. :+1:

Thanks for your reading,

Sincerely,
Yang

**Comment by hobailey** [comment]
Hi Yang, 
Thanks for your feedback and ideas. We already have an enum with all currencies - I appreciate this might be confusing at first, but the importance is that the acceptable currencies are controlled from the API and do not throw an exception initially - this is because certain currencies are available or not under certain conditions (a certain payment method for example) or certain clients. Therefore we have decided not to change the SDK in this way to remain as flexible as possible.
Thanks again.
